//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQToSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_UserInfo
    {
        public int UserID { get; set; }
        public string Account { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int UserType { get; set; }
        public Nullable<int> FunctionRoleID { get; set; }
        public bool IsUse { get; set; }
        public string Phone { get; set; }
        public string EMail { get; set; }
        public string OpenId { get; set; }
        public string HeadPortrait { get; set; }
        public string DeviceToken { get; set; }
        public bool IsStaOnline { get; set; }
        public bool IsCustomerServices { get; set; }
        public string Title { get; set; }
        public string WeChatNo { get; set; }
        public string RongCloudToken { get; set; }
        public Nullable<bool> IsPublic { get; set; }
        public string BlocCode { get; set; }
        public string DeptCode { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string NXTOpenId { get; set; }
    }
}
