<?xml version="1.0" encoding="utf-8"?><Database Name="EFOS.Master" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.3.179;Initial Catalog=EFOS.Master;Persist Security Info=True;User ID=sa" SettingsObjectName="LINQToSQL.Properties.Settings" SettingsPropertyName="EFOS_MasterConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CustomerInfo" Member="CustomerInfo">
    <Type Name="CustomerInfo">
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="CompName" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="CompAddress" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Linkman" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="State" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RegTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CheckTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserNo" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="ActivateCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CompUrl" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.OutputData" Method="OutputData">
    <Parameter Name="tablename" Type="System.String" DbType="NVarChar(128)" />
    <Return Type="System.Int32" />
  </Function>
</Database>